# Generated by Django 5.1.3 on 2024-12-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users_words_admins_learnedwords_wordsinprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password_hash',
            field=models.CharField(),
        ),
    ]
