# Generated by Django 5.1.7 on 2025-05-08 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'max_length': 'Неверный формат имени пользователя.'}, max_length=20, unique=True)),
                ('email', models.CharField(error_messages={'max_length': 'Неверный формат электронной почты.'}, max_length=20, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_email_verificated', models.BooleanField(default=False)),
                ('account_created_at', models.DateTimeField(auto_now_add=True)),
                ('password_changed_at', models.DateTimeField(auto_now=True)),
                ('last_day_online', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('word_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'UserActivity',
            },
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('established_post', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Admins',
            },
        ),
    ]
