# Generated by Django 5.1.7 on 2025-04-26 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'max_length': 'Неверный формат имени пользователя.'}, max_length=20, unique=True)),
                ('email', models.CharField(error_messages={'max_length': 'Неверный формат электронной почты.'}, max_length=20, unique=True)),
                ('english_level', models.CharField(error_messages={'max_length': 'Убедитесь, что это поле не содержит более 2 символов.'}, max_length=2)),
                ('is_email_verificated', models.BooleanField(default=False)),
                ('account_created_at', models.DateTimeField(auto_now_add=True)),
                ('password_changed_at', models.DateTimeField(auto_now=True)),
                ('last_day_online', models.DateTimeField(auto_now_add=True)),
                ('days_in_berserk', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('established_post', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Admins',
            },
        ),
    ]
