# Generated by Django 5.1.7 on 2025-05-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_initial'),
        ('vocabulary', '0004_alter_words_unique_together_remove_stage_next_stage_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['last_day_online'], name='Users_last_da_772a5e_idx'),
        ),
    ]
