# Generated by Django 5.1.7 on 2025-05-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_users_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='days_in_berserk',
        ),
    ]
