# Generated by Django 5.1.7 on 2025-05-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_users_users_last_da_772a5e_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
