# Generated by Django 5.1.7 on 2025-05-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_users_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
