# Generated by Django 5.1.1 on 2024-12-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(error_messages={'max_length': 'Неверный формат электронной почты.'}, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='english_level',
            field=models.CharField(error_messages={'max_length': 'Убедитесь, что это поле не содержит более 2 символов.'}, max_length=2),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(error_messages={'max_length': 'Неверный формат имени пользователя.'}, max_length=20, unique=True),
        ),
    ]
