# Generated by Django 5.1.7 on 2025-04-02 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id_word', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=30, unique=True)),
                ('translate_word', models.CharField(max_length=30)),
                ('word_level', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'Words',
            },
        ),
        migrations.CreateModel(
            name='LearnedWords',
            fields=[
                ('id_learned_word', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.words')),
            ],
            options={
                'db_table': 'LearnedWords',
                'unique_together': {('word', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WordsInProgress',
            fields=[
                ('id_word_in_progress', models.AutoField(primary_key=True, serialize=False)),
                ('number_views', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.words')),
            ],
            options={
                'db_table': 'WordsInProgress',
                'unique_together': {('word', 'user')},
            },
        ),
    ]
