# Generated by Django 5.1.7 on 2025-05-08 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'PartsOfSpeech',
            },
        ),
        migrations.CreateModel(
            name='WordLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'db_table': 'WordLevels',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('interactions_needed', models.IntegerField()),
                ('next_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocabulary.stage')),
            ],
            options={
                'db_table': 'Stages',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id_word', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=30, unique=True)),
                ('translate_word', models.CharField(max_length=30)),
                ('rating', models.IntegerField(default=1)),
                ('part_of_speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.partofspeech')),
                ('word_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.wordlevel')),
            ],
            options={
                'db_table': 'Words',
            },
        ),
        migrations.CreateModel(
            name='UserWordProgress',
            fields=[
                ('id_progress', models.AutoField(primary_key=True, serialize=False)),
                ('interaction_count', models.IntegerField(default=0)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('stage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vocabulary.stage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.words')),
            ],
            options={
                'db_table': 'UserWordProgress',
                'unique_together': {('word', 'user')},
            },
        ),
    ]
