# Generated by Django 5.1.7 on 2025-04-26 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id_word', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=30, unique=True)),
                ('part_of_speech', models.CharField(max_length=50)),
                ('translate_word', models.CharField(max_length=30)),
                ('word_level', models.CharField(max_length=2)),
                ('rating', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Words',
            },
        ),
        migrations.CreateModel(
            name='UserWordProgress',
            fields=[
                ('id_progress', models.AutoField(primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('introduction', 'Introduction'), ('active_recall', 'Active Recall'), ('consolidation', 'Consolidation'), ('spaced_repetition', 'Spaced Repetition'), ('active_usage', 'Active Usage')], default='introduction', max_length=20)),
                ('interaction_count', models.IntegerField(default=0)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.words')),
            ],
            options={
                'db_table': 'UserWordProgress',
                'unique_together': {('word', 'user')},
            },
        ),
    ]
