# Generated by Django 5.1.7 on 2025-05-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='word',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='words',
            unique_together={('word', 'translate_word')},
        ),
    ]
