# Generated by Django 5.1.7 on 2025-04-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='part_of_speech',
            field=models.CharField(default='nan', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='words',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
