# Generated by Django 5.1.7 on 2025-05-08 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_words_word_alter_words_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwordprogress',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='vocabulary.words'),
        ),
    ]
