# Generated by Django 5.1.7 on 2025-04-22 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('vocabulary', '0002_words_part_of_speech_words_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordsinprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wordsinprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wordsinprogress',
            name='word',
        ),
        migrations.CreateModel(
            name='UserWordProgress',
            fields=[
                ('id_progress', models.AutoField(primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('introduction', 'Introduction'), ('active_recall', 'Active Recall'), ('consolidation', 'Consolidation'), ('spaced_repetition', 'Spaced Repetition'), ('active_usage', 'Active Usage')], default='introduction', max_length=20)),
                ('interaction_count', models.IntegerField(default=0)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.words')),
            ],
            options={
                'db_table': 'UserWordProgress',
                'unique_together': {('word', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='LearnedWords',
        ),
        migrations.DeleteModel(
            name='WordsInProgress',
        ),
    ]
