# Generated by Django 5.1.7 on 2025-05-08 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_alter_userwordprogress_word'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='words',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='stage',
            name='next_stage',
        ),
        migrations.AlterField(
            model_name='stage',
            name='interactions_needed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='wordlevel',
            name='level',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='words',
            name='translate_word',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='words',
            name='word',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='userwordprogress',
            index=models.Index(fields=['user', 'word'], name='UserWordPro_user_id_7b8b09_idx'),
        ),
        migrations.AddIndex(
            model_name='userwordprogress',
            index=models.Index(fields=['user', 'stage'], name='UserWordPro_user_id_d83253_idx'),
        ),
        migrations.AddIndex(
            model_name='userwordprogress',
            index=models.Index(fields=['word'], name='UserWordPro_word_id_bf9bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='words',
            index=models.Index(fields=['word_level'], name='Words_word_le_c3477c_idx'),
        ),
        migrations.AddIndex(
            model_name='words',
            index=models.Index(fields=['part_of_speech'], name='Words_part_of_899b8d_idx'),
        ),
        migrations.AlterModelTable(
            name='partofspeech',
            table='PartOfSpeech',
        ),
        migrations.AlterModelTable(
            name='stage',
            table='Stage',
        ),
        migrations.AlterModelTable(
            name='wordlevel',
            table='WordLevel',
        ),
    ]
