# Generated by Django 5.1.7 on 2025-05-08 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_alter_words_unique_together_remove_stage_next_stage_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userwordprogress',
            name='UserWordPro_user_id_7b8b09_idx',
        ),
        migrations.RemoveIndex(
            model_name='userwordprogress',
            name='UserWordPro_user_id_d83253_idx',
        ),
        migrations.RemoveIndex(
            model_name='userwordprogress',
            name='UserWordPro_word_id_bf9bb4_idx',
        ),
        migrations.RemoveIndex(
            model_name='words',
            name='Words_word_le_c3477c_idx',
        ),
        migrations.RemoveIndex(
            model_name='words',
            name='Words_part_of_899b8d_idx',
        ),
        migrations.AddField(
            model_name='stage',
            name='next_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocabulary.stage'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='interactions_needed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='wordlevel',
            name='level',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='words',
            name='translate_word',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='words',
            name='word',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='words',
            unique_together={('word', 'translate_word')},
        ),
        migrations.AlterModelTable(
            name='partofspeech',
            table='PartsOfSpeech',
        ),
        migrations.AlterModelTable(
            name='stage',
            table='Stages',
        ),
        migrations.AlterModelTable(
            name='wordlevel',
            table='WordLevels',
        ),
    ]
